# This is a basic workflow to help you get started with Actions

name: Test Secrets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GLOBAL_SECRET: ${{ secrets.GLOBAL_SECRET }}
      ENV_SECRET: ${{ secrets.SECRET_SOMETHING }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Echo Global Seen
        run: |
          if [ "$GLOBAL_SECRET" != "" ] 
          then 
            echo "Global Var Present" 
          else 
            echo "Global Var Not Present" 
          fi
      - name: Echo Environment seen
        run: | 
          if [ "$ENV_SECRET" != "" ] 
          then 
            echo "Env Var Present"
          else 
            echo "Env Var Not Present" 
          fi
